-- View of 7.3.6
CREATE OR REPLACE VIEW TUITION_SHEET AS
	SELECT s.INSTNM, c.TUITIONFEE_IN as 'TUITION IN-STATE', c.TUITIONFEE_OUT as 'TUITION OUT-STATE', c.TUITIONFEE_OUT - c.TUITIONFEE_IN as 'DIFFERENCE'
		FROM school s
			INNER JOIN cost c
				ON s.OPEID = c.OPEID
		WHERE 
			(s.RELAFFIL IS NULL -- No religious affiliation
				OR s.RELAFFIL = -2) -- Religious affiliation is not applicable
			AND c.TUITIONFEE_IN IS NOT NULL
			AND c.TUITIONFEE_OUT IS NOT NULL
		GROUP BY s.INSTNM;

SELECT * FROM TUITION_SHEET;


-- View of 7.1.2
CREATE OR REPLACE VIEW INSTITUTION_RELIGION AS
	SELECT s.INSTNM, r.RELAFFIL_VALUE
	FROM school s
		LEFT JOIN relaffil r 
			ON r.relaffil_id = s.relaffil;
			
SELECT * FROM INSTITUTION_RELIGION;


-- View of 7.2.2
CREATE OR REPLACE VIEW NORTHEAST_SCHOOLS AS
SELECT s.INSTNM 
	FROM school s 
	WHERE 
		s.REGION IN ( SELECT r.REGION_ID 
							FROM region r 
							WHERE 
								r.REGION_VALUE LIKE '%New England%'
								OR r.REGION_VALUE LIKE '%Mid East%');

SELECT * FROM NORTHEAST_SCHOOLS;


-- View of 7.3.2
CREATE OR REPLACE VIEW STATE_SAT_AVG AS
SELECT s.STABBR AS 'STATE', AVG(a.SAT_AVG_ALL) AS ADM_SAT_AVG
	FROM admissions a
		INNER JOIN school s
			ON a.OPEID = s.OPEID
	WHERE a.SAT_AVG_ALL IS NOT NULL
	GROUP BY s.STABBR;
	
SELECT * FROM STATE_SAT_AVG;
